/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectSlugRouteImport } from './routes/project/$slug'

const ProjectsLazyRouteImport = createFileRoute('/projects')()
const HealthcheckLazyRouteImport = createFileRoute('/healthcheck')()
const IndexLazyRouteImport = createFileRoute('/')()

const ProjectsLazyRoute = ProjectsLazyRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))
const HealthcheckLazyRoute = HealthcheckLazyRouteImport.update({
  id: '/healthcheck',
  path: '/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/healthcheck.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/healthcheck': typeof HealthcheckLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/healthcheck': typeof HealthcheckLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/healthcheck': typeof HealthcheckLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/healthcheck' | '/projects' | '/project/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/healthcheck' | '/projects' | '/project/$slug'
  id: '__root__' | '/' | '/healthcheck' | '/projects' | '/project/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  HealthcheckLazyRoute: typeof HealthcheckLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcheck': {
      id: '/healthcheck'
      path: '/healthcheck'
      fullPath: '/healthcheck'
      preLoaderRoute: typeof HealthcheckLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  HealthcheckLazyRoute: HealthcheckLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
